env:
  es2021: true
  node: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules: {}
overrides: [
  {
    files: ["*.js"],
    rules: {
      no-useless-escape: off,
      import/extensions: off,
      no-console: off,
      no-await-in-loop: off
    }
  }
]
